import type { Metadata } from "next";
import "./globals.css";
import "./globals2.css";
import { Toaster } from "react-hot-toast";
import MainLayout from "./components/mainLayout";
import AppContextProvider from "./context/AppContextProvider";
import { GoogleOAuthProvider } from "@react-oauth/google";

export const metadata: Metadata = {
  title: "My Practice",
  description: "Generated by create next app",
};

interface MainBodyProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: MainBodyProps) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        />
      </head>
      <body>
        <AppContextProvider>
          <div className="vh100 d-flex">
            <GoogleOAuthProvider
              clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID as string}
            >
              <MainLayout>{children}</MainLayout>
              <Toaster position="top-center" />
            </GoogleOAuthProvider>
          </div>
        </AppContextProvider>
      </body>
    </html>
  );
}
